### ISSUE TITLE
Transparent Background for Flask Logo = Confusion for Dark Mode Users

### ISSUE THREAD

**Issue by baspin94** [learn-co-curriculum/python-p4-intro-to-flask#3]
### Canvas Link

https://learning.flatironschool.com/courses/6259/pages/intro-to-flask?module_item_id=547375

### Concern

This isn’t an ‘issue’ so much as a suggestion: anyone viewing the Canvas lesson or the GitHub README with dark mode enabled (which is a lot of people, including me)  will not be able to see that there is an image of the Flask logo at the top of the ‘History of Flask’ section because it’s black text on a transparent background. I was confused about why there was such a big gap at the top of that section until I hovered over it and saw the link to the source image.

### Suggested Changes

It would be helpful to update that with a version of the image that has a solid background of some sort.

**Comment by professor-ben** [comment]
I honestly had no idea that Canvas had a dark mode until now. I'll find an image with better contrast and update this shortly.

-Ben
